[2024-08-14T04:40:41.603+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-14T04:40:42.114+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_etl_dag.get_municipios manual__2024-08-14T04:39:50.483167+00:00 [queued]>
[2024-08-14T04:40:42.137+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_etl_dag.get_municipios manual__2024-08-14T04:39:50.483167+00:00 [queued]>
[2024-08-14T04:40:42.147+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-08-14T04:40:42.276+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): get_municipios> on 2024-08-14 04:39:50.483167+00:00
[2024-08-14T04:40:42.285+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=3388) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-14T04:40:42.289+0000] {standard_task_runner.py:64} INFO - Started process 3390 to run task
[2024-08-14T04:40:42.288+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'weather_etl_dag', 'get_municipios', 'manual__2024-08-14T04:39:50.483167+00:00', '--job-id', '101', '--raw', '--subdir', 'DAGS_FOLDER/weather_etl_dag.py', '--cfg-path', '/tmp/tmpvu9lsroq']
[2024-08-14T04:40:42.291+0000] {standard_task_runner.py:91} INFO - Job 101: Subtask get_municipios
[2024-08-14T04:40:42.476+0000] {task_command.py:426} INFO - Running <TaskInstance: weather_etl_dag.get_municipios manual__2024-08-14T04:39:50.483167+00:00 [running]> on host 712d18ef94ea
[2024-08-14T04:40:42.892+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_etl_dag' AIRFLOW_CTX_TASK_ID='get_municipios' AIRFLOW_CTX_EXECUTION_DATE='2024-08-14T04:39:50.483167+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-14T04:39:50.483167+00:00'
[2024-08-14T04:40:42.900+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-14T04:40:43.715+0000] {logging_mixin.py:188} INFO - Conexi√≥n establecida con Redshift.
[2024-08-14T04:40:43.716+0000] {logging_mixin.py:188} INFO - Ejecutando la consulta SQL...
[2024-08-14T04:40:43.725+0000] {warnings.py:112} WARNING - /opt/***/dags/weather_etl_dag.py:82: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_municipios = pd.read_sql_query(query, conn)

[2024-08-14T04:40:43.880+0000] {logging_mixin.py:188} INFO - Consulta ejecutada, numero de registros obtenidos:18
[2024-08-14T04:40:43.882+0000] {logging_mixin.py:188} INFO - conexion a redshift cerrada
[2024-08-14T04:40:43.995+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-08-14T04:40:43.997+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-14T04:40:44.025+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=weather_etl_dag, task_id=get_municipios, run_id=manual__2024-08-14T04:39:50.483167+00:00, execution_date=20240814T043950, start_date=20240814T044042, end_date=20240814T044044
[2024-08-14T04:40:44.223+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-08-14T04:40:44.240+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
