[2024-08-19T00:48:34.569+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-19T00:48:34.594+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_etl_dag.translate_and_clean_data scheduled__2024-08-18T00:00:00+00:00 [queued]>
[2024-08-19T00:48:34.602+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_etl_dag.translate_and_clean_data scheduled__2024-08-18T00:00:00+00:00 [queued]>
[2024-08-19T00:48:34.652+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-08-19T00:48:34.943+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): translate_and_clean_data> on 2024-08-18 00:00:00+00:00
[2024-08-19T00:48:34.949+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=6367) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-19T00:48:34.951+0000] {standard_task_runner.py:64} INFO - Started process 6369 to run task
[2024-08-19T00:48:34.951+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'weather_etl_dag', 'translate_and_clean_data', 'scheduled__2024-08-18T00:00:00+00:00', '--job-id', '213', '--raw', '--subdir', 'DAGS_FOLDER/weather_etl_dag.py', '--cfg-path', '/tmp/tmpcjssvvd0']
[2024-08-19T00:48:34.953+0000] {standard_task_runner.py:91} INFO - Job 213: Subtask translate_and_clean_data
[2024-08-19T00:48:35.211+0000] {task_command.py:426} INFO - Running <TaskInstance: weather_etl_dag.translate_and_clean_data scheduled__2024-08-18T00:00:00+00:00 [running]> on host b7290fbe53d7
[2024-08-19T00:48:35.944+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_etl_dag' AIRFLOW_CTX_TASK_ID='translate_and_clean_data' AIRFLOW_CTX_EXECUTION_DATE='2024-08-18T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-18T00:00:00+00:00'
[2024-08-19T00:48:35.946+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-19T00:48:37.186+0000] {logging_mixin.py:188} INFO - recuperando dataframe de pronosticos desde xcom
[2024-08-19T00:48:37.255+0000] {logging_mixin.py:188} INFO - numero de registros en pronosticos:18
[2024-08-19T00:48:37.431+0000] {logging_mixin.py:188} INFO - Pronósticos antes de limpiar y traducir:    cve_mun            municipio  ... wind_kph  humidity
0        1    AMEALCO DE BONFIL  ...     20.9        73
1        2      PINAL DE AMOLES  ...     22.7        74
2        3          ARROYO SECO  ...     15.1        82
3        4  CADEREYTA DE MONTES  ...     16.9        77
4        5                COLON  ...     22.7        74

[5 rows x 10 columns]
[2024-08-19T00:49:34.273+0000] {logging_mixin.py:188} INFO - Pronósticos después de limpiar y traducir:    cve_mun            municipio  ... viento_kph  humedad
0        1    Amealco De Bonfil  ...       20.9       73
1        2      Pinal De Amoles  ...       22.7       74
2        3          Arroyo Seco  ...       15.1       82
3        4  Cadereyta De Montes  ...       16.9       77
4        5                Colon  ...       22.7       74

[5 rows x 10 columns]
[2024-08-19T00:49:34.344+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-08-19T00:49:34.344+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-19T00:49:34.352+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=weather_etl_dag, task_id=translate_and_clean_data, run_id=scheduled__2024-08-18T00:00:00+00:00, execution_date=20240818T000000, start_date=20240819T004834, end_date=20240819T004934
[2024-08-19T00:49:34.445+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-08-19T00:49:34.468+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-08-19T00:49:34.506+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-09-05T18:18:19.760+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-05T18:18:19.848+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_etl_dag.translate_and_clean_data scheduled__2024-08-18T00:00:00+00:00 [queued]>
[2024-09-05T18:18:19.881+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_etl_dag.translate_and_clean_data scheduled__2024-08-18T00:00:00+00:00 [queued]>
[2024-09-05T18:18:19.891+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 2
[2024-09-05T18:18:19.999+0000] {taskinstance.py:2879} INFO - Executing <Task(PythonOperator): translate_and_clean_data> on 2024-08-18 00:00:00+00:00
[2024-09-05T18:18:20.007+0000] {warnings.py:112} WARNING - /usr/local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1078) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-05T18:18:20.012+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'weather_etl_dag', 'translate_and_clean_data', 'scheduled__2024-08-18T00:00:00+00:00', '--job-id', '105', '--raw', '--subdir', 'DAGS_FOLDER/weather_etl_dag.py', '--cfg-path', '/tmp/tmpdg93ee23']
[2024-09-05T18:18:20.018+0000] {standard_task_runner.py:72} INFO - Started process 1082 to run task
[2024-09-05T18:18:20.018+0000] {standard_task_runner.py:105} INFO - Job 105: Subtask translate_and_clean_data
[2024-09-05T18:18:20.330+0000] {task_command.py:467} INFO - Running <TaskInstance: weather_etl_dag.translate_and_clean_data scheduled__2024-08-18T00:00:00+00:00 [running]> on host 0b8eaea5e88c
[2024-09-05T18:18:21.387+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_etl_dag' AIRFLOW_CTX_TASK_ID='translate_and_clean_data' AIRFLOW_CTX_EXECUTION_DATE='2024-08-18T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-18T00:00:00+00:00'
[2024-09-05T18:18:21.389+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-05T18:18:21.417+0000] {logging_mixin.py:190} INFO - Recuperando DataFrame de pronósticos desde XCom
[2024-09-05T18:18:21.527+0000] {logging_mixin.py:190} INFO - Número de registros en pronósticos: 18
[2024-09-05T18:18:21.541+0000] {logging_mixin.py:190} INFO - Pronósticos antes de limpiar y traducir:    cve_mun            municipio  ... wind_kph  humidity
0        1    AMEALCO DE BONFIL  ...     18.0        78
1        2      PINAL DE AMOLES  ...     16.6        75
2        3          ARROYO SECO  ...     17.3        84
3        4  CADEREYTA DE MONTES  ...     14.0        79
4        5                COLON  ...     16.6        75

[5 rows x 10 columns]
[2024-09-05T18:19:18.212+0000] {local_task_job_runner.py:341} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2024-09-05T18:19:18.213+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
[2024-09-05T18:19:18.215+0000] {process_utils.py:132} INFO - Sending 15 to group 1082. PIDs of all processes in the group: [1082]
[2024-09-05T18:19:18.215+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 1082
[2024-09-05T18:19:18.216+0000] {taskinstance.py:3083} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-09-05T18:19:18.308+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-05T18:19:18.333+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=1082, status='terminated', exitcode=0, started='18:18:19') (1082) terminated with exit code 0
