[2024-09-05T23:47:53.093+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-05T23:47:53.264+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_etl_dag.translate_and_clean_data scheduled__2024-08-18T00:00:00+00:00 [queued]>
[2024-09-05T23:47:53.523+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_etl_dag.translate_and_clean_data scheduled__2024-08-18T00:00:00+00:00 [queued]>
[2024-09-05T23:47:53.524+0000] {taskinstance.py:2856} INFO - Starting attempt 2 of 3
[2024-09-05T23:47:53.699+0000] {taskinstance.py:2879} INFO - Executing <Task(PythonOperator): translate_and_clean_data> on 2024-08-18 00:00:00+00:00
[2024-09-05T23:47:53.704+0000] {warnings.py:112} WARNING - /usr/local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=335) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-05T23:47:53.706+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'weather_etl_dag', 'translate_and_clean_data', 'scheduled__2024-08-18T00:00:00+00:00', '--job-id', '156', '--raw', '--subdir', 'DAGS_FOLDER/weather_etl_dag.py', '--cfg-path', '/tmp/tmp2zj9s9y7']
[2024-09-05T23:47:53.739+0000] {standard_task_runner.py:72} INFO - Started process 348 to run task
[2024-09-05T23:47:53.768+0000] {standard_task_runner.py:105} INFO - Job 156: Subtask translate_and_clean_data
[2024-09-05T23:47:53.932+0000] {task_command.py:467} INFO - Running <TaskInstance: weather_etl_dag.translate_and_clean_data scheduled__2024-08-18T00:00:00+00:00 [running]> on host da9f5d3bcb59
[2024-09-05T23:48:00.604+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_etl_dag' AIRFLOW_CTX_TASK_ID='translate_and_clean_data' AIRFLOW_CTX_EXECUTION_DATE='2024-08-18T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-18T00:00:00+00:00'
[2024-09-05T23:48:00.606+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-05T23:49:07.066+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-09-05T23:49:07.078+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-05T23:49:07.079+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=weather_etl_dag, task_id=translate_and_clean_data, run_id=scheduled__2024-08-18T00:00:00+00:00, execution_date=20240818T000000, start_date=20240905T234753, end_date=20240905T234907
[2024-09-05T23:49:07.245+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2024-09-05T23:49:19.112+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
[2024-09-05T23:49:19.126+0000] {taskinstance.py:3891} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-09-05T23:49:19.202+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
