[2024-08-14T04:21:28.692+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-14T04:21:29.025+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_etl_dag.insert_weather_data manual__2024-08-14T04:18:29.011010+00:00 [queued]>
[2024-08-14T04:21:29.037+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_etl_dag.insert_weather_data manual__2024-08-14T04:18:29.011010+00:00 [queued]>
[2024-08-14T04:21:29.079+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-08-14T04:21:29.144+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): insert_weather_data> on 2024-08-14 04:18:29.011010+00:00
[2024-08-14T04:21:29.152+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=2482) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-14T04:21:29.156+0000] {standard_task_runner.py:64} INFO - Started process 2484 to run task
[2024-08-14T04:21:29.157+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'weather_etl_dag', 'insert_weather_data', 'manual__2024-08-14T04:18:29.011010+00:00', '--job-id', '75', '--raw', '--subdir', 'DAGS_FOLDER/weather_etl_dag.py', '--cfg-path', '/tmp/tmptlsl0ho9']
[2024-08-14T04:21:29.160+0000] {standard_task_runner.py:91} INFO - Job 75: Subtask insert_weather_data
[2024-08-14T04:21:29.247+0000] {task_command.py:426} INFO - Running <TaskInstance: weather_etl_dag.insert_weather_data manual__2024-08-14T04:18:29.011010+00:00 [running]> on host 712d18ef94ea
[2024-08-14T04:21:29.429+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_etl_dag' AIRFLOW_CTX_TASK_ID='insert_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2024-08-14T04:18:29.011010+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-14T04:18:29.011010+00:00'
[2024-08-14T04:21:29.431+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-14T04:21:32.593+0000] {logging_mixin.py:188} INFO - Todos los pronósticos han sido insertados con éxito en Redshift.
[2024-08-14T04:21:32.594+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-08-14T04:21:32.595+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-14T04:21:32.613+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=weather_etl_dag, task_id=insert_weather_data, run_id=manual__2024-08-14T04:18:29.011010+00:00, execution_date=20240814T041829, start_date=20240814T042129, end_date=20240814T042132
[2024-08-14T04:21:32.752+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-08-14T04:21:32.826+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-08-14T04:21:32.899+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
