[2024-09-05T00:49:13.035+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-05T00:49:13.062+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_etl_dag.get_municipios manual__2024-09-05T00:32:19.554061+00:00 [queued]>
[2024-09-05T00:49:13.088+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_etl_dag.get_municipios manual__2024-09-05T00:32:19.554061+00:00 [queued]>
[2024-09-05T00:49:13.092+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 2
[2024-09-05T00:49:13.204+0000] {taskinstance.py:2879} INFO - Executing <Task(PythonOperator): get_municipios> on 2024-09-05 00:32:19.554061+00:00
[2024-09-05T00:49:13.213+0000] {warnings.py:112} WARNING - /usr/local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1017) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-05T00:49:13.215+0000] {standard_task_runner.py:72} INFO - Started process 1022 to run task
[2024-09-05T00:49:13.221+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'weather_etl_dag', 'get_municipios', 'manual__2024-09-05T00:32:19.554061+00:00', '--job-id', '121', '--raw', '--subdir', 'DAGS_FOLDER/weather_etl_dag.py', '--cfg-path', '/tmp/tmp089b41q1']
[2024-09-05T00:49:13.241+0000] {standard_task_runner.py:105} INFO - Job 121: Subtask get_municipios
[2024-09-05T00:49:13.455+0000] {task_command.py:467} INFO - Running <TaskInstance: weather_etl_dag.get_municipios manual__2024-09-05T00:32:19.554061+00:00 [running]> on host b778581f4b0f
[2024-09-05T00:49:14.158+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_etl_dag' AIRFLOW_CTX_TASK_ID='get_municipios' AIRFLOW_CTX_EXECUTION_DATE='2024-09-05T00:32:19.554061+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-05T00:32:19.554061+00:00'
[2024-09-05T00:49:14.161+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-05T00:49:14.753+0000] {logging_mixin.py:190} INFO - Conexión establecida con Redshift.
[2024-09-05T00:49:14.754+0000] {logging_mixin.py:190} INFO - Ejecutando la consulta SQL...
[2024-09-05T00:49:14.765+0000] {warnings.py:112} WARNING - /root/***/dags/weather_etl.py:29: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_municipios = pd.read_sql_query(query, conn)

[2024-09-05T00:49:14.912+0000] {logging_mixin.py:190} INFO - Consulta ejecutada, número de registros obtenidos: 18
[2024-09-05T00:49:14.913+0000] {logging_mixin.py:190} INFO - Conexión a Redshift cerrada
[2024-09-05T00:49:15.308+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-09-05T00:49:15.348+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-05T00:49:15.349+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=weather_etl_dag, task_id=get_municipios, run_id=manual__2024-09-05T00:32:19.554061+00:00, execution_date=20240905T003219, start_date=20240905T004913, end_date=20240905T004915
[2024-09-05T00:49:15.550+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2024-09-05T00:49:15.607+0000] {taskinstance.py:3891} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-09-05T00:49:15.661+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
