[2024-08-17T15:15:53.255+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-17T15:15:53.280+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_etl_dag.insert_weather_data manual__2024-08-17T15:13:11.389709+00:00 [queued]>
[2024-08-17T15:15:53.289+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_etl_dag.insert_weather_data manual__2024-08-17T15:13:11.389709+00:00 [queued]>
[2024-08-17T15:15:53.304+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-08-17T15:15:53.493+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): insert_weather_data> on 2024-08-17 15:13:11.389709+00:00
[2024-08-17T15:15:53.498+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=302) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-17T15:15:53.502+0000] {standard_task_runner.py:64} INFO - Started process 304 to run task
[2024-08-17T15:15:53.502+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'weather_etl_dag', 'insert_weather_data', 'manual__2024-08-17T15:13:11.389709+00:00', '--job-id', '195', '--raw', '--subdir', 'DAGS_FOLDER/weather_etl_dag.py', '--cfg-path', '/tmp/tmp1tnwa69m']
[2024-08-17T15:15:53.505+0000] {standard_task_runner.py:91} INFO - Job 195: Subtask insert_weather_data
[2024-08-17T15:15:53.581+0000] {task_command.py:426} INFO - Running <TaskInstance: weather_etl_dag.insert_weather_data manual__2024-08-17T15:13:11.389709+00:00 [running]> on host b7290fbe53d7
[2024-08-17T15:15:53.778+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_etl_dag' AIRFLOW_CTX_TASK_ID='insert_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2024-08-17T15:13:11.389709+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-17T15:13:11.389709+00:00'
[2024-08-17T15:15:53.779+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-17T15:16:01.027+0000] {logging_mixin.py:188} INFO - Todos los pronósticos han sido insertados con éxito en Redshift.
[2024-08-17T15:16:01.028+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-08-17T15:16:01.029+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-17T15:16:01.037+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=weather_etl_dag, task_id=insert_weather_data, run_id=manual__2024-08-17T15:13:11.389709+00:00, execution_date=20240817T151311, start_date=20240817T151553, end_date=20240817T151601
[2024-08-17T15:16:01.158+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-08-17T15:16:01.178+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-08-17T15:16:01.220+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
