[2024-09-05T00:33:14.748+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-05T00:33:14.783+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_etl_dag.get_municipios manual__2024-09-05T00:27:08.901871+00:00 [queued]>
[2024-09-05T00:33:14.803+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_etl_dag.get_municipios manual__2024-09-05T00:27:08.901871+00:00 [queued]>
[2024-09-05T00:33:14.808+0000] {taskinstance.py:2856} INFO - Starting attempt 2 of 2
[2024-09-05T00:33:15.007+0000] {taskinstance.py:2879} INFO - Executing <Task(PythonOperator): get_municipios> on 2024-09-05 00:27:08.901871+00:00
[2024-09-05T00:33:15.155+0000] {warnings.py:112} WARNING - /usr/local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=215) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-05T00:33:15.170+0000] {standard_task_runner.py:72} INFO - Started process 219 to run task
[2024-09-05T00:33:15.173+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'weather_etl_dag', 'get_municipios', 'manual__2024-09-05T00:27:08.901871+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/weather_etl_dag.py', '--cfg-path', '/tmp/tmprgdltgmt']
[2024-09-05T00:33:15.191+0000] {standard_task_runner.py:105} INFO - Job 25: Subtask get_municipios
[2024-09-05T00:33:15.541+0000] {task_command.py:467} INFO - Running <TaskInstance: weather_etl_dag.get_municipios manual__2024-09-05T00:27:08.901871+00:00 [running]> on host b778581f4b0f
[2024-09-05T00:33:15.963+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_etl_dag' AIRFLOW_CTX_TASK_ID='get_municipios' AIRFLOW_CTX_EXECUTION_DATE='2024-09-05T00:27:08.901871+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-05T00:27:08.901871+00:00'
[2024-09-05T00:33:15.972+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-05T00:33:16.741+0000] {logging_mixin.py:190} INFO - Conexión establecida con Redshift.
[2024-09-05T00:33:16.745+0000] {logging_mixin.py:190} INFO - Ejecutando la consulta SQL...
[2024-09-05T00:33:16.830+0000] {warnings.py:112} WARNING - /root/***/dags/weather_etl.py:29: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_municipios = pd.read_sql_query(query, conn)

[2024-09-05T00:33:16.986+0000] {logging_mixin.py:190} INFO - Consulta ejecutada, número de registros obtenidos: 18
[2024-09-05T00:33:16.991+0000] {logging_mixin.py:190} INFO - Conexión a Redshift cerrada
[2024-09-05T00:33:17.269+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-09-05T00:33:17.349+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-05T00:33:17.356+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=weather_etl_dag, task_id=get_municipios, run_id=manual__2024-09-05T00:27:08.901871+00:00, execution_date=20240905T002708, start_date=20240905T003314, end_date=20240905T003317
[2024-09-05T00:33:17.453+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2024-09-05T00:33:17.531+0000] {taskinstance.py:3891} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-09-05T00:33:17.573+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
