[2024-09-06T00:06:12.307+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-06T00:06:12.327+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_etl_dag.translate_and_clean_data scheduled__2024-08-29T00:00:00+00:00 [queued]>
[2024-09-06T00:06:12.346+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_etl_dag.translate_and_clean_data scheduled__2024-08-29T00:00:00+00:00 [queued]>
[2024-09-06T00:06:12.348+0000] {taskinstance.py:2856} INFO - Starting attempt 2 of 2
[2024-09-06T00:06:12.429+0000] {taskinstance.py:2879} INFO - Executing <Task(PythonOperator): translate_and_clean_data> on 2024-08-29 00:00:00+00:00
[2024-09-06T00:06:12.438+0000] {warnings.py:112} WARNING - /usr/local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=799) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-06T00:06:12.445+0000] {standard_task_runner.py:72} INFO - Started process 801 to run task
[2024-09-06T00:06:12.440+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'weather_etl_dag', 'translate_and_clean_data', 'scheduled__2024-08-29T00:00:00+00:00', '--job-id', '198', '--raw', '--subdir', 'DAGS_FOLDER/weather_etl_dag.py', '--cfg-path', '/tmp/tmpbo9bha83']
[2024-09-06T00:06:12.449+0000] {standard_task_runner.py:105} INFO - Job 198: Subtask translate_and_clean_data
[2024-09-06T00:06:12.576+0000] {task_command.py:467} INFO - Running <TaskInstance: weather_etl_dag.translate_and_clean_data scheduled__2024-08-29T00:00:00+00:00 [running]> on host da9f5d3bcb59
[2024-09-06T00:06:13.280+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_etl_dag' AIRFLOW_CTX_TASK_ID='translate_and_clean_data' AIRFLOW_CTX_EXECUTION_DATE='2024-08-29T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-29T00:00:00+00:00'
[2024-09-06T00:06:13.281+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-06T00:07:17.095+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-09-06T00:07:17.120+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-06T00:07:17.122+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=weather_etl_dag, task_id=translate_and_clean_data, run_id=scheduled__2024-08-29T00:00:00+00:00, execution_date=20240829T000000, start_date=20240906T000612, end_date=20240906T000717
[2024-09-06T00:07:17.201+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2024-09-06T00:07:20.726+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
[2024-09-06T00:07:20.729+0000] {taskinstance.py:3891} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-09-06T00:07:20.800+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
