[2024-08-14T04:34:19.929+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-14T04:34:20.126+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_etl_dag.send_email_with_csv manual__2024-08-14T04:31:22.695827+00:00 [queued]>
[2024-08-14T04:34:20.138+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_etl_dag.send_email_with_csv manual__2024-08-14T04:31:22.695827+00:00 [queued]>
[2024-08-14T04:34:20.140+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-08-14T04:34:20.226+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): send_email_with_csv> on 2024-08-14 04:31:22.695827+00:00
[2024-08-14T04:34:20.237+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'weather_etl_dag', 'send_email_with_csv', 'manual__2024-08-14T04:31:22.695827+00:00', '--job-id', '89', '--raw', '--subdir', 'DAGS_FOLDER/weather_etl_dag.py', '--cfg-path', '/tmp/tmpajzv0z2u']
[2024-08-14T04:34:20.249+0000] {standard_task_runner.py:91} INFO - Job 89: Subtask send_email_with_csv
[2024-08-14T04:34:20.243+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=2892) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-14T04:34:20.258+0000] {standard_task_runner.py:64} INFO - Started process 2894 to run task
[2024-08-14T04:34:20.351+0000] {task_command.py:426} INFO - Running <TaskInstance: weather_etl_dag.send_email_with_csv manual__2024-08-14T04:31:22.695827+00:00 [running]> on host 712d18ef94ea
[2024-08-14T04:34:20.697+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_etl_dag' AIRFLOW_CTX_TASK_ID='send_email_with_csv' AIRFLOW_CTX_EXECUTION_DATE='2024-08-14T04:31:22.695827+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-14T04:31:22.695827+00:00'
[2024-08-14T04:34:20.699+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-14T04:34:20.721+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-14T04:34:20.722+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/weather_etl_dag.py", line 412, in send_email_with_csv
    smtp_user = Variable.get("from_email")  # Correo de Gmail
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable from_email does not exist'
[2024-08-14T04:34:20.733+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=weather_etl_dag, task_id=send_email_with_csv, run_id=manual__2024-08-14T04:31:22.695827+00:00, execution_date=20240814T043122, start_date=20240814T043420, end_date=20240814T043420
[2024-08-14T04:34:20.783+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 89 for task send_email_with_csv ('Variable from_email does not exist'; 2894)
[2024-08-14T04:34:20.822+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-08-14T04:34:20.830+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
